#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football_League
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FootBall_League")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_Team(Table_Team instance);
    partial void UpdateTable_Team(Table_Team instance);
    partial void DeleteTable_Team(Table_Team instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Football_League.Properties.Settings.Default.FootBall_LeagueConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_Team> Table_Teams
		{
			get
			{
				return this.GetTable<Table_Team>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Delete_Team")]
		public int Delete_Team([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string team_name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), team_name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Insert_Team")]
		public int Insert_Team([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string team_name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), team_name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Mehman_Win")]
		public int Mehman_Win([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string mehman_team_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> goal_zadeh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> goal_khordeh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mehman_team_name, goal_zadeh, goal_khordeh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Mizban_Win")]
		public int Mizban_Win([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string mizban_team_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> goal_zadeh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> goal_khordeh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mizban_team_name, goal_zadeh, goal_khordeh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Update_Information")]
		public int Update_Information()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Mehman_Lose")]
		public int Mehman_Lose([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string mehman_team_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> goal_zadeh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> goal_khordeh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mehman_team_name, goal_zadeh, goal_khordeh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Mizban_Lose")]
		public int Mizban_Lose([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string mizban_team_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> goal_zadeh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> goal_khordeh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mizban_team_name, goal_zadeh, goal_khordeh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Update_Team")]
		public int Update_Team([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string team_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> win, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> draw, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lose, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> goal_zadeh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> goal_khordeh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), team_name, win, draw, lose, goal_zadeh, goal_khordeh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Draw_Teams")]
		public int Draw_Teams([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string mizban_team_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string mehman_team_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> goal_zadeh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mizban_team_name, mehman_team_name, goal_zadeh);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Teams")]
	public partial class Table_Team : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Team_Name;
		
		private System.Nullable<int> _Tedad_Bazi;
		
		private System.Nullable<int> _Win;
		
		private System.Nullable<int> _Draw;
		
		private System.Nullable<int> _Lose;
		
		private System.Nullable<int> _Point;
		
		private System.Nullable<int> _Goal_Zadeh;
		
		private System.Nullable<int> _Goal_Khordeh;
		
		private System.Nullable<int> _Tafazol;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTeam_NameChanging(string value);
    partial void OnTeam_NameChanged();
    partial void OnTedad_BaziChanging(System.Nullable<int> value);
    partial void OnTedad_BaziChanged();
    partial void OnWinChanging(System.Nullable<int> value);
    partial void OnWinChanged();
    partial void OnDrawChanging(System.Nullable<int> value);
    partial void OnDrawChanged();
    partial void OnLoseChanging(System.Nullable<int> value);
    partial void OnLoseChanged();
    partial void OnPointChanging(System.Nullable<int> value);
    partial void OnPointChanged();
    partial void OnGoal_ZadehChanging(System.Nullable<int> value);
    partial void OnGoal_ZadehChanged();
    partial void OnGoal_KhordehChanging(System.Nullable<int> value);
    partial void OnGoal_KhordehChanged();
    partial void OnTafazolChanging(System.Nullable<int> value);
    partial void OnTafazolChanged();
    #endregion
		
		public Table_Team()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Team_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Team_Name
		{
			get
			{
				return this._Team_Name;
			}
			set
			{
				if ((this._Team_Name != value))
				{
					this.OnTeam_NameChanging(value);
					this.SendPropertyChanging();
					this._Team_Name = value;
					this.SendPropertyChanged("Team_Name");
					this.OnTeam_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tedad_Bazi", DbType="Int")]
		public System.Nullable<int> Tedad_Bazi
		{
			get
			{
				return this._Tedad_Bazi;
			}
			set
			{
				if ((this._Tedad_Bazi != value))
				{
					this.OnTedad_BaziChanging(value);
					this.SendPropertyChanging();
					this._Tedad_Bazi = value;
					this.SendPropertyChanged("Tedad_Bazi");
					this.OnTedad_BaziChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Win", DbType="Int")]
		public System.Nullable<int> Win
		{
			get
			{
				return this._Win;
			}
			set
			{
				if ((this._Win != value))
				{
					this.OnWinChanging(value);
					this.SendPropertyChanging();
					this._Win = value;
					this.SendPropertyChanged("Win");
					this.OnWinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Draw", DbType="Int")]
		public System.Nullable<int> Draw
		{
			get
			{
				return this._Draw;
			}
			set
			{
				if ((this._Draw != value))
				{
					this.OnDrawChanging(value);
					this.SendPropertyChanging();
					this._Draw = value;
					this.SendPropertyChanged("Draw");
					this.OnDrawChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lose", DbType="Int")]
		public System.Nullable<int> Lose
		{
			get
			{
				return this._Lose;
			}
			set
			{
				if ((this._Lose != value))
				{
					this.OnLoseChanging(value);
					this.SendPropertyChanging();
					this._Lose = value;
					this.SendPropertyChanged("Lose");
					this.OnLoseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Point", DbType="Int")]
		public System.Nullable<int> Point
		{
			get
			{
				return this._Point;
			}
			set
			{
				if ((this._Point != value))
				{
					this.OnPointChanging(value);
					this.SendPropertyChanging();
					this._Point = value;
					this.SendPropertyChanged("Point");
					this.OnPointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Goal_Zadeh", DbType="Int")]
		public System.Nullable<int> Goal_Zadeh
		{
			get
			{
				return this._Goal_Zadeh;
			}
			set
			{
				if ((this._Goal_Zadeh != value))
				{
					this.OnGoal_ZadehChanging(value);
					this.SendPropertyChanging();
					this._Goal_Zadeh = value;
					this.SendPropertyChanged("Goal_Zadeh");
					this.OnGoal_ZadehChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Goal_Khordeh", DbType="Int")]
		public System.Nullable<int> Goal_Khordeh
		{
			get
			{
				return this._Goal_Khordeh;
			}
			set
			{
				if ((this._Goal_Khordeh != value))
				{
					this.OnGoal_KhordehChanging(value);
					this.SendPropertyChanging();
					this._Goal_Khordeh = value;
					this.SendPropertyChanged("Goal_Khordeh");
					this.OnGoal_KhordehChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tafazol", DbType="Int")]
		public System.Nullable<int> Tafazol
		{
			get
			{
				return this._Tafazol;
			}
			set
			{
				if ((this._Tafazol != value))
				{
					this.OnTafazolChanging(value);
					this.SendPropertyChanging();
					this._Tafazol = value;
					this.SendPropertyChanged("Tafazol");
					this.OnTafazolChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
